# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import runpy
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton
from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel, QLineEdit, QVBoxLayout, QWidget
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.add_student = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_student.setGeometry(QtCore.QRect(230, 0, 281, 91))
        self.add_student.setObjectName("add_student")
        self.add_student.setCheckable(False)
        self.add_student.clicked.connect(self.face_gen())

        self.show_list_student = QtWidgets.QPushButton(parent=self.centralwidget)
        self.show_list_student.setGeometry(QtCore.QRect(230, 240, 281, 91))
        self.show_list_student.setObjectName("show_list_student")

        self.scan_mode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.scan_mode.setGeometry(QtCore.QRect(230, 460, 281, 91))
        self.scan_mode.setObjectName("scan_mode")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_student.setText(_translate("MainWindow", "Добавить студента"))
        self.show_list_student.setText(_translate("MainWindow", "Просмотреть список студентов"))
        self.scan_mode.setText(_translate("MainWindow", "Перейти в режим сканирования"))

    def scanning(self):
        runpy.run_module('main')

    def face_train(self):
        runpy.run_module('face_train')

    def face_gen(self):
        runpy.run_module('face_gen')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
